-- Initial YAHO schema. Generated-equivalent baseline from prisma/schema.prisma.
CREATE TYPE "Role" AS ENUM ('ADMIN', 'TEACHER');
CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'UNSPECIFIED');
CREATE TYPE "RelationshipType" AS ENUM ('FRIEND', 'SIBLING');
CREATE TYPE "ConsentType" AS ENUM ('PRIVACY', 'SENSITIVE_INFO', 'PHOTO_SHARE', 'PHOTO_MARKETING');
CREATE TYPE "ConsentAction" AS ENUM ('AGREED', 'REVOKED');
CREATE TYPE "ProgramStatus" AS ENUM ('ACTIVE', 'INACTIVE');
CREATE TYPE "ClassStatus" AS ENUM ('SCHEDULED', 'COMPLETED', 'CANCELLED');
CREATE TYPE "ClassCancelReason" AS ENUM ('WEATHER', 'SAFETY', 'MINIMUM_ENROLLMENT', 'OPERATION', 'OTHER');
CREATE TYPE "ReservationStatus" AS ENUM ('RESERVED', 'CANCELLED', 'COMPLETED', 'NO_SHOW');
CREATE TYPE "ReservationCancelReason" AS ENUM ('PERSONAL', 'ILLNESS', 'SCHEDULE', 'WEATHER', 'DUPLICATE', 'OPERATION', 'OTHER');
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT');
CREATE TYPE "PaymentStatus" AS ENUM ('PAID', 'PARTIAL_REFUNDED', 'REFUNDED', 'CANCELLED');
CREATE TYPE "PaymentMethod" AS ENUM ('CARD', 'TRANSFER', 'CASH', 'OTHER');
CREATE TYPE "PayerType" AS ENUM ('GUARDIAN', 'ORGANIZATION');
CREATE TYPE "RefundReason" AS ENUM ('PERSONAL', 'ILLNESS', 'WEATHER', 'SCHEDULE', 'DUPLICATE_PAYMENT', 'CLASS_CANCELLED', 'OPERATION', 'OTHER');
CREATE TYPE "RefundStatus" AS ENUM ('REQUESTED', 'COMPLETED', 'CANCELLED');

CREATE TABLE "User" ("id" TEXT NOT NULL, "email" TEXT NOT NULL, "name" TEXT NOT NULL, "password" TEXT, "role" "Role" NOT NULL DEFAULT 'ADMIN', "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Child" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "birthDate" DATE, "gender" "Gender" NOT NULL DEFAULT 'UNSPECIFIED', "guardianName" TEXT, "guardianPhone" TEXT, "memo" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "registeredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Child_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ChildSafetyInfo" ("id" TEXT NOT NULL, "childId" TEXT NOT NULL, "allergies" TEXT, "emergencyNotes" TEXT, "emergencyContactName" TEXT, "emergencyContactPhone" TEXT, "emergencyContactRelation" TEXT, "updatedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ChildSafetyInfo_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ChildConsent" ("id" TEXT NOT NULL, "childId" TEXT NOT NULL, "consentType" "ConsentType" NOT NULL, "action" "ConsentAction" NOT NULL, "recordedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "memo" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ChildConsent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Relationship" ("id" TEXT NOT NULL, "childAId" TEXT NOT NULL, "childBId" TEXT NOT NULL, "type" "RelationshipType" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Relationship_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Teacher" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT, "memo" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Teacher_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Program" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "targetAgeMin" INTEGER, "targetAgeMax" INTEGER, "defaultDuration" INTEGER, "defaultPrice" INTEGER NOT NULL DEFAULT 0, "status" "ProgramStatus" NOT NULL DEFAULT 'ACTIVE', "memo" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Program_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ClassSchedule" ("id" TEXT NOT NULL, "programId" TEXT NOT NULL, "startsAt" TIMESTAMP(3) NOT NULL, "endsAt" TIMESTAMP(3) NOT NULL, "location" TEXT NOT NULL, "capacity" INTEGER NOT NULL DEFAULT 8, "status" "ClassStatus" NOT NULL DEFAULT 'SCHEDULED', "memo" TEXT, "cancelledAt" TIMESTAMP(3), "cancelReason" "ClassCancelReason", "cancelDetail" TEXT, "cancelledById" TEXT, "insured" BOOLEAN NOT NULL DEFAULT false, "insurer" TEXT, "insurancePolicyNo" TEXT, "safetyMemo" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ClassSchedule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ClassTeacher" ("id" TEXT NOT NULL, "classScheduleId" TEXT NOT NULL, "teacherId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ClassTeacher_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Reservation" ("id" TEXT NOT NULL, "childId" TEXT NOT NULL, "classScheduleId" TEXT NOT NULL, "status" "ReservationStatus" NOT NULL DEFAULT 'RESERVED', "attendance" "AttendanceStatus", "reservedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "memo" TEXT, "cancelledAt" TIMESTAMP(3), "cancelReason" "ReservationCancelReason", "cancelDetail" TEXT, "cancelledById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Reservation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" TEXT NOT NULL, "payerType" "PayerType" NOT NULL DEFAULT 'GUARDIAN', "payerName" TEXT, "method" "PaymentMethod" NOT NULL, "status" "PaymentStatus" NOT NULL DEFAULT 'PAID', "paidAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "totalAmount" INTEGER NOT NULL, "memo" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentItem" ("id" TEXT NOT NULL, "paymentId" TEXT NOT NULL, "reservationId" TEXT NOT NULL, "amount" INTEGER NOT NULL, "discountAmount" INTEGER NOT NULL DEFAULT 0, "paidAmount" INTEGER NOT NULL, "refundedAmount" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PaymentItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Refund" ("id" TEXT NOT NULL, "paymentItemId" TEXT NOT NULL, "amount" INTEGER NOT NULL, "reason" "RefundReason" NOT NULL, "reasonDetail" TEXT, "status" "RefundStatus" NOT NULL DEFAULT 'COMPLETED', "refundedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Refund_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "ChildSafetyInfo_childId_key" ON "ChildSafetyInfo"("childId");
CREATE UNIQUE INDEX "Relationship_childAId_childBId_type_key" ON "Relationship"("childAId", "childBId", "type");
CREATE UNIQUE INDEX "ClassTeacher_classScheduleId_teacherId_key" ON "ClassTeacher"("classScheduleId", "teacherId");
CREATE UNIQUE INDEX "Reservation_classScheduleId_childId_key" ON "Reservation"("classScheduleId", "childId");
CREATE UNIQUE INDEX "PaymentItem_reservationId_key" ON "PaymentItem"("reservationId");
CREATE INDEX "Child_name_idx" ON "Child"("name"); CREATE INDEX "Child_guardianPhone_idx" ON "Child"("guardianPhone"); CREATE INDEX "Child_isActive_idx" ON "Child"("isActive");
CREATE INDEX "ChildConsent_childId_consentType_recordedAt_idx" ON "ChildConsent"("childId", "consentType", "recordedAt");
CREATE INDEX "Relationship_childAId_idx" ON "Relationship"("childAId"); CREATE INDEX "Relationship_childBId_idx" ON "Relationship"("childBId");
CREATE INDEX "Program_status_idx" ON "Program"("status"); CREATE INDEX "ClassSchedule_startsAt_idx" ON "ClassSchedule"("startsAt"); CREATE INDEX "ClassSchedule_status_idx" ON "ClassSchedule"("status"); CREATE INDEX "ClassSchedule_programId_idx" ON "ClassSchedule"("programId");
CREATE INDEX "Reservation_childId_idx" ON "Reservation"("childId"); CREATE INDEX "Reservation_status_idx" ON "Reservation"("status"); CREATE INDEX "Payment_paidAt_idx" ON "Payment"("paidAt"); CREATE INDEX "Payment_status_idx" ON "Payment"("status"); CREATE INDEX "PaymentItem_paymentId_idx" ON "PaymentItem"("paymentId"); CREATE INDEX "Refund_paymentItemId_idx" ON "Refund"("paymentItemId"); CREATE INDEX "Refund_refundedAt_idx" ON "Refund"("refundedAt");

ALTER TABLE "ChildSafetyInfo" ADD CONSTRAINT "ChildSafetyInfo_childId_fkey" FOREIGN KEY ("childId") REFERENCES "Child"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ChildSafetyInfo" ADD CONSTRAINT "ChildSafetyInfo_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ChildConsent" ADD CONSTRAINT "ChildConsent_childId_fkey" FOREIGN KEY ("childId") REFERENCES "Child"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Relationship" ADD CONSTRAINT "Relationship_childAId_fkey" FOREIGN KEY ("childAId") REFERENCES "Child"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Relationship" ADD CONSTRAINT "Relationship_childBId_fkey" FOREIGN KEY ("childBId") REFERENCES "Child"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ClassSchedule" ADD CONSTRAINT "ClassSchedule_programId_fkey" FOREIGN KEY ("programId") REFERENCES "Program"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "ClassSchedule" ADD CONSTRAINT "ClassSchedule_cancelledById_fkey" FOREIGN KEY ("cancelledById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "ClassTeacher" ADD CONSTRAINT "ClassTeacher_classScheduleId_fkey" FOREIGN KEY ("classScheduleId") REFERENCES "ClassSchedule"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ClassTeacher" ADD CONSTRAINT "ClassTeacher_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "Teacher"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_childId_fkey" FOREIGN KEY ("childId") REFERENCES "Child"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_classScheduleId_fkey" FOREIGN KEY ("classScheduleId") REFERENCES "ClassSchedule"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_cancelledById_fkey" FOREIGN KEY ("cancelledById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PaymentItem" ADD CONSTRAINT "PaymentItem_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "PaymentItem" ADD CONSTRAINT "PaymentItem_reservationId_fkey" FOREIGN KEY ("reservationId") REFERENCES "Reservation"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Refund" ADD CONSTRAINT "Refund_paymentItemId_fkey" FOREIGN KEY ("paymentItemId") REFERENCES "PaymentItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Refund" ADD CONSTRAINT "Refund_processedById_fkey" FOREIGN KEY ("processedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Constraints intentionally kept alongside the initial schema migration.
ALTER TABLE "Relationship" ADD CONSTRAINT "relationship_not_self" CHECK ("childAId" <> "childBId"), ADD CONSTRAINT "relationship_sorted_pair" CHECK ("childAId" < "childBId");
ALTER TABLE "ClassSchedule" ADD CONSTRAINT "class_capacity_positive" CHECK ("capacity" >= 1), ADD CONSTRAINT "class_time_order" CHECK ("endsAt" > "startsAt");
ALTER TABLE "PaymentItem" ADD CONSTRAINT "payment_item_amount_nonneg" CHECK ("amount" >= 0 AND "discountAmount" >= 0 AND "paidAmount" >= 0), ADD CONSTRAINT "payment_item_paid_calc" CHECK ("paidAmount" = "amount" - "discountAmount"), ADD CONSTRAINT "payment_item_refund_limit" CHECK ("refundedAmount" >= 0 AND "refundedAmount" <= "paidAmount");
ALTER TABLE "Refund" ADD CONSTRAINT "refund_amount_positive" CHECK ("amount" > 0);
