"use client";

import { useEffect, useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { createCompanionInvitation, notifyApplicationDeposit, revokeCompanionInvitation } from "./completion-actions";

export function CompletionGuide({ bankName, accountNumber, accountHolder, payerName, applications }: { bankName: string; accountNumber: string; accountHolder: string; payerName: string | null; applications: Array<{ id: string; childName: string | null; quotedAmount: number }> }) {
  const [clientReady, setClientReady] = useState(false);
  useEffect(() => { setClientReady(true); }, []);
  const [notice, setNotice] = useState<string>();
  const [companionUrl, setCompanionUrl] = useState<string>();
  const [pending, startTransition] = useTransition();
  const total = applications.reduce((sum, application) => sum + application.quotedAmount, 0);
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); setNotice("복사했습니다."); } catch { setNotice("복사하지 못했습니다. 길게 눌러 복사해주세요."); } }
  return <section className="space-y-4 rounded-lg border bg-white p-4"><h2 className="text-lg font-semibold">무통장 입금 안내</h2><ul className="space-y-2 text-sm">{applications.map((application) => <li className="flex justify-between gap-4" key={application.id}><span>{application.childName ?? "아이"}</span><strong>{application.quotedAmount.toLocaleString("ko-KR")}원</strong></li>)}</ul><p className="flex justify-between border-t pt-3 text-sm"><span>합계</span><strong>{total.toLocaleString("ko-KR")}원</strong></p><dl className="space-y-2 text-sm"><div className="flex justify-between gap-3"><dt>은행</dt><dd>{bankName}</dd></div><div className="flex justify-between gap-3"><dt>계좌번호</dt><dd>{accountNumber}</dd></div><div className="flex justify-between gap-3"><dt>예금주</dt><dd>{accountHolder}</dd></div><div className="flex justify-between gap-3"><dt>입금자명</dt><dd>{payerName ?? "-"}</dd></div></dl><div className="flex flex-wrap gap-2"><Button disabled={!clientReady} onClick={() => copy(accountNumber)} type="button">계좌번호 복사</Button><Button disabled={!clientReady} onClick={() => copy(String(total))} type="button">금액 복사</Button><Button disabled={!clientReady || !payerName} onClick={() => payerName && copy(payerName)} type="button">입금자명 복사</Button></div><Button disabled={!clientReady || pending} onClick={() => startTransition(async () => { const result = await notifyApplicationDeposit(); setNotice(result.notified ? "입금 알림을 기록했습니다. 운영자가 실제 입금을 확인한 뒤 예약을 확정합니다." : "현재 신청에서는 입금 알림을 기록할 수 없습니다."); })} type="button">{pending ? "처리 중..." : "입금했어요"}</Button><div className="border-t pt-4"><p className="mb-2 text-sm font-medium">동행 초대</p><div className="flex flex-wrap gap-2"><Button disabled={!clientReady || pending} onClick={() => startTransition(async () => { const result = await createCompanionInvitation(); if (result.url) { setCompanionUrl(result.url); setNotice("동행 초대 링크를 만들었습니다."); } else setNotice(result.error ?? "동행 초대장을 만들 수 없습니다."); })} type="button">동행 초대 링크 만들기</Button>{companionUrl ? <Button disabled={!clientReady} onClick={() => copy(`${window.location.origin}${companionUrl}`)} type="button">초대 링크 복사</Button> : null}{companionUrl ? <Button disabled={!clientReady || pending} onClick={() => startTransition(async () => { const result = await revokeCompanionInvitation(companionUrl); setCompanionUrl(undefined); setNotice(result.revoked ? "동행 초대 링크를 취소했습니다." : "동행 초대 링크를 취소할 수 없습니다."); })} type="button">초대 취소</Button> : null}</div></div>{notice ? <p aria-live="polite" className="text-sm text-slate-600" role="status">{notice}</p> : null}</section>;
}
